#include "Vertex.h"

namespace lre::Vertex {
	std::unordered_map<uint64_t, function> MAP = {
		{ color_flag, C1::VertexArray },
		{ color_flag | normal_flag, C1N1::VertexArray },
		{ color_flag | normal_flag | tex_flag, C1N1T1::VertexArray },
		{ color_flag | normal_flag | uv_flag, C1N1UV1::VertexArray },
		{ color_flag | normal_flag | uv_flag | tex_flag, C1N1UV1T1::VertexArray },
		{ color_flag | normal_flag | uv_flag | uvw_flag, C1N1UV1UVW1::VertexArray },
		{ color_flag | normal_flag | uv_flag | uvw_flag | tex_flag, C1N1UV1UVW1T1::VertexArray },
		{ color_flag | normal_flag | uvw_flag, C1N1UVW1::VertexArray },
		{ color_flag | normal_flag | uvw_flag | tex_flag, C1N1UVW1T1::VertexArray },
		{ color_flag | tex_flag, C1T1::VertexArray },
		{ color_flag | uv_flag, C1UV1::VertexArray },
		{ color_flag | uv_flag | tex_flag, C1UV1T1::VertexArray },
		{ color_flag | uv_flag | uvw_flag, C1UV1UVW1::VertexArray },
		{ color_flag | uv_flag | uvw_flag | tex_flag, C1UV1UVW1T1::VertexArray },
		{ color_flag | uvw_flag, C1UVW1::VertexArray },
		{ color_flag | uvw_flag | tex_flag, C1UVW1T1::VertexArray },
		{ normal_flag, N1::VertexArray },
		{ normal_flag | tex_flag, N1T1::VertexArray },
		{ normal_flag | uv_flag, N1UV1::VertexArray },
		{ normal_flag | uv_flag | tex_flag, N1UV1T1::VertexArray },
		{ normal_flag | uv_flag | uvw_flag, N1UV1UVW1::VertexArray },
		{ normal_flag | uv_flag | uvw_flag | tex_flag, N1UV1UVW1T1::VertexArray },
		{ normal_flag | uvw_flag, N1UVW1::VertexArray },
		{ normal_flag | uvw_flag | tex_flag, N1UVW1T1::VertexArray },
		{ 0, NullVertex::VertexArray },
		{ position_flag, P1::VertexArray },
		{ position_flag | color_flag, P1C1::VertexArray },
		{ position_flag | color_flag | normal_flag, P1C1N1::VertexArray },
		{ position_flag | color_flag | normal_flag | tex_flag, P1C1N1T1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag, P1C1N1UV1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag | tex_flag, P1C1N1UV1T1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag | uvw_flag, P1C1N1UV1UVW1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag | uvw_flag | tex_flag, P1C1N1UV1UVW1T1::VertexArray },
		{ position_flag | color_flag | normal_flag | uvw_flag, P1C1N1UVW1::VertexArray },
		{ position_flag | color_flag | normal_flag | uvw_flag | tex_flag, P1C1N1UVW1T1::VertexArray },
		{ position_flag | color_flag | tex_flag, P1C1T1::VertexArray },
		{ position_flag | color_flag | uv_flag, P1C1UV1::VertexArray },
		{ position_flag | color_flag | uv_flag | tex_flag, P1C1UV1T1::VertexArray },
		{ position_flag | color_flag | uv_flag | uvw_flag, P1C1UV1UVW1::VertexArray },
		{ position_flag | color_flag | uv_flag | uvw_flag | tex_flag, P1C1UV1UVW1T1::VertexArray },
		{ position_flag | color_flag | uvw_flag, P1C1UVW1::VertexArray },
		{ position_flag | color_flag | uvw_flag | tex_flag, P1C1UVW1T1::VertexArray },
		{ position_flag | normal_flag, P1N1::VertexArray },
		{ position_flag | normal_flag | tex_flag, P1N1T1::VertexArray },
		{ position_flag | normal_flag | uv_flag, P1N1UV1::VertexArray },
		{ position_flag | normal_flag | uv_flag | tex_flag, P1N1UV1T1::VertexArray },
		{ position_flag | normal_flag | uv_flag | uvw_flag, P1N1UV1UVW1::VertexArray },
		{ position_flag | normal_flag | uv_flag | uvw_flag | tex_flag, P1N1UV1UVW1T1::VertexArray },
		{ position_flag | normal_flag | uvw_flag, P1N1UVW1::VertexArray },
		{ position_flag | normal_flag | uvw_flag | tex_flag, P1N1UVW1T1::VertexArray },
		{ position_flag | tex_flag, P1T1::VertexArray },
		{ position_flag | uv_flag, P1UV1::VertexArray },
		{ position_flag | uv_flag | tex_flag, P1UV1T1::VertexArray },
		{ position_flag | uv_flag | uvw_flag, P1UV1UVW1::VertexArray },
		{ position_flag | uv_flag | uvw_flag | tex_flag, P1UV1UVW1T1::VertexArray },
		{ position_flag | uvw_flag, P1UVW1::VertexArray },
		{ position_flag | uvw_flag | tex_flag, P1UVW1T1::VertexArray },
		{ tex_flag, T1::VertexArray },
		{ uv_flag, UV1::VertexArray },
		{ uv_flag | tex_flag, UV1T1::VertexArray },
		{ uv_flag | uvw_flag, UV1UVW1::VertexArray },
		{ uv_flag | uvw_flag | tex_flag, UV1UVW1T1::VertexArray },
		{ uvw_flag, UVW1::VertexArray },
		{ uvw_flag | tex_flag, UVW1T1::VertexArray },
	};
}
